// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7w8Id0pNTB9F5G-MUDJCFgvrbxXt26vc',
    appId: '1:324980708177:web:fd9d1436d121620c0f3970',
    messagingSenderId: '324980708177',
    projectId: 'plant-health-monitor-58b53',
    authDomain: 'plant-health-monitor-58b53.firebaseapp.com',
    storageBucket: 'plant-health-monitor-58b53.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKfAmUm8yR5MzvNKkG5VDjZ0BaPy-sVLs',
    appId: '1:324980708177:android:31b7fc2b350afd0f0f3970',
    messagingSenderId: '324980708177',
    projectId: 'plant-health-monitor-58b53',
    storageBucket: 'plant-health-monitor-58b53.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATSyKp5fWZb6vpT-Be6jw6HQkic3p7jmM',
    appId: '1:324980708177:ios:9f208bd61c0479d80f3970',
    messagingSenderId: '324980708177',
    projectId: 'plant-health-monitor-58b53',
    storageBucket: 'plant-health-monitor-58b53.appspot.com',
    iosBundleId: 'com.example.plantHealthMonitor',
  );
}
